set nocompatible  " so that multiline works

let mapleader=','

if empty(glob('~/.vim/autoload/plug.vim'))
  echo "Downloading Plug..."
  silent !curl -fsSLo $DOTFILES/vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

call plug#end()
